[[plugins]]
repo = 'neovim/nvim-lspconfig'
on_event = 'BufRead'
hook_source = '''
lua << EOF
local capabilities = vim.lsp.protocol.make_client_capabilities()
capabilities.textDocument.completion.completionItem.snippetSupport = true

local lspconfig = require'lspconfig'
lspconfig.gopls.setup{capabilities = capabilities}
EOF
'''

[[plugins]]
repo = 'vim-denops/denops.vim'

[[plugins]]
repo = 'Shougo/ddc-source-around'
on_source = 'ddc.vim'

[[plugins]]
repo = 'Shougo/ddc-matcher_head'
on_source = 'ddc.vim'

[[plugins]]
repo = 'Shougo/ddc-sorter_rank'
on_source = 'ddc.vim'

[[plugins]]
repo = 'Shougo/ddc-ui-native'
on_source = 'ddc.vim'

[[plugins]]
repo = 'Shougo/ddc.vim'
depends = ['denops.vim', 'nvim-lspconfig']
on_event = ['InsertEnter']
hook_source = '''
call ddc#custom#patch_global(
      \ 'sources', ['around', 'nvim-lsp']
      \ )
call ddc#custom#patch_global('ui', 'native')
call ddc#custom#patch_global('sourceOptions', {
      \ '_': {
      \   'matchers': ['matcher_head'],
      \   'sorters': ['sorter_rank'],
      \ },
      \ 'nvim-lsp': {
      \   'mark': 'lsp', 
      \   'forceCompletionPattern': '\.\w*|:\w*|->\w*',
      \  },
      \ })

call ddc#enable()
'''

# (1) display no lsp candidates
# [[plugins]]
# repo = 'Shougo/ddc-source-nvim-lsp'
# on_source = 'nvim-lspconfig'
# rev = '70086994e3d83e65eb4aed6888b84d4b0b2f3aeb'

# (2) '[ddc] source: nvim-lsp "onCompleteDone()" failed' after selecting lsp candidates
[[plugins]]
repo = 'Shougo/ddc-source-nvim-lsp'
on_source = 'nvim-lspconfig'
rev = '738b86b5c16ee8f396d9437e6aea17780e325ef1'

# (3) work
# [[plugins]]
# repo = 'Shougo/ddc-source-nvim-lsp'
# on_source = 'nvim-lspconfig'
# rev = '72197a06b7fa84d657432dede1110f24ac158329'
